name: Build and Commit Frontend

on:
  push:
    branches:
      - master # Adjust to your default branch

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify your Node.js version

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build the React app
        working-directory: frontend
        run: npm run build # This generates the 'build' directory

      - name: Commit and Push Build Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Add and commit build artifacts
          cd frontend
          git add .
          git commit -m "Add build artifacts" || echo "No changes to commit"

          # Push changes to the repository
          git push origin master
      - name: Push new code to AWS EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su
            cd /home/ubuntu/Docker-Hunter
            git pull origin master
            docker stop $(docker ps -q)
            docker rm -f $(docker ps -a -q)
            docker rmi -f $(docker images -q)
            docker build . -t bughunter
            docker run -d -p 8080:8080 bughunter
