name: Build and Commit Frontend

on:
  push:
    branches:
      - master # Adjust to your default branch

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify your Node.js version

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build the React app
        working-directory: frontend
        run: npm run build

      - name: Upload build to AWS EC2
        env:
          KEY: ${{ secrets.KEY }}
          SSH_USER: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
        run: |
          echo "$KEY" > private_key.pem
          chmod 600 private_key.pem
          rsync -avz --delete -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" frontend/dist/ $SSH_USER@$HOST:/home/ubuntu/Docker-Hunter/frontend/dist
      - name: Push new code to AWS EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            /home/ubuntu/Docker-Hunter/deploy.sh
